// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// quatProd
Rcpp::NumericVector quatProd(const Rcpp::NumericVector& q1, const Rcpp::NumericVector& q2);
RcppExport SEXP _RcppQuaternions_quatProd(SEXP q1SEXP, SEXP q2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type q2(q2SEXP);
    rcpp_result_gen = Rcpp::wrap(quatProd(q1, q2));
    return rcpp_result_gen;
END_RCPP
}
// fromAxisAngle
Rcpp::NumericVector fromAxisAngle(const Eigen::VectorXd& axis, const double& angle);
RcppExport SEXP _RcppQuaternions_fromAxisAngle(SEXP axisSEXP, SEXP angleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type axis(axisSEXP);
    Rcpp::traits::input_parameter< const double& >::type angle(angleSEXP);
    rcpp_result_gen = Rcpp::wrap(fromAxisAngle(axis, angle));
    return rcpp_result_gen;
END_RCPP
}
// fromQuaternion
Eigen::MatrixXd fromQuaternion(const Rcpp::NumericVector& v);
RcppExport SEXP _RcppQuaternions_fromQuaternion(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fromQuaternion(v));
    return rcpp_result_gen;
END_RCPP
}
// toAxisAngle
Rcpp::List toAxisAngle(const Rcpp::NumericVector& v);
RcppExport SEXP _RcppQuaternions_toAxisAngle(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(toAxisAngle(v));
    return rcpp_result_gen;
END_RCPP
}
// getRotation
Rcpp::NumericVector getRotation(const Eigen::VectorXd& a, const Eigen::VectorXd& b);
RcppExport SEXP _RcppQuaternions_getRotation(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(getRotation(a, b));
    return rcpp_result_gen;
END_RCPP
}
// AngleAxis2quaternion
Rcpp::NumericVector AngleAxis2quaternion(const double& angl, const Eigen::VectorXd& axs);
RcppExport SEXP _RcppQuaternions_AngleAxis2quaternion(SEXP anglSEXP, SEXP axsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type angl(anglSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type axs(axsSEXP);
    rcpp_result_gen = Rcpp::wrap(AngleAxis2quaternion(angl, axs));
    return rcpp_result_gen;
END_RCPP
}
// Matrix2AxisAngle
Rcpp::List Matrix2AxisAngle(const Eigen::MatrixXd& m);
RcppExport SEXP _RcppQuaternions_Matrix2AxisAngle(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(Matrix2AxisAngle(m));
    return rcpp_result_gen;
END_RCPP
}
// toQuaternion
Rcpp::NumericVector toQuaternion(const Eigen::MatrixXd& m);
RcppExport SEXP _RcppQuaternions_toQuaternion(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(toQuaternion(m));
    return rcpp_result_gen;
END_RCPP
}
// AngleAxis2matrix
Eigen::MatrixXd AngleAxis2matrix(const double& angl, const Eigen::VectorXd& axs);
RcppExport SEXP _RcppQuaternions_AngleAxis2matrix(SEXP anglSEXP, SEXP axsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type angl(anglSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type axs(axsSEXP);
    rcpp_result_gen = Rcpp::wrap(AngleAxis2matrix(angl, axs));
    return rcpp_result_gen;
END_RCPP
}
// normalized
Rcpp::NumericVector normalized(const Rcpp::NumericVector& v);
RcppExport SEXP _RcppQuaternions_normalized(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(normalized(v));
    return rcpp_result_gen;
END_RCPP
}
// slerp_
Rcpp::NumericVector slerp_(const Rcpp::NumericVector& q1, const Rcpp::NumericVector& q2, const double t);
RcppExport SEXP _RcppQuaternions_slerp_(SEXP q1SEXP, SEXP q2SEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(slerp_(q1, q2, t));
    return rcpp_result_gen;
END_RCPP
}
// rversor_
Rcpp::NumericVector rversor_();
RcppExport SEXP _RcppQuaternions_rversor_() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rversor_());
    return rcpp_result_gen;
END_RCPP
}
// rversors_
Rcpp::NumericMatrix rversors_(const unsigned n);
RcppExport SEXP _RcppQuaternions_rversors_(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const unsigned >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rversors_(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppQuaternions_quatProd", (DL_FUNC) &_RcppQuaternions_quatProd, 2},
    {"_RcppQuaternions_fromAxisAngle", (DL_FUNC) &_RcppQuaternions_fromAxisAngle, 2},
    {"_RcppQuaternions_fromQuaternion", (DL_FUNC) &_RcppQuaternions_fromQuaternion, 1},
    {"_RcppQuaternions_toAxisAngle", (DL_FUNC) &_RcppQuaternions_toAxisAngle, 1},
    {"_RcppQuaternions_getRotation", (DL_FUNC) &_RcppQuaternions_getRotation, 2},
    {"_RcppQuaternions_AngleAxis2quaternion", (DL_FUNC) &_RcppQuaternions_AngleAxis2quaternion, 2},
    {"_RcppQuaternions_Matrix2AxisAngle", (DL_FUNC) &_RcppQuaternions_Matrix2AxisAngle, 1},
    {"_RcppQuaternions_toQuaternion", (DL_FUNC) &_RcppQuaternions_toQuaternion, 1},
    {"_RcppQuaternions_AngleAxis2matrix", (DL_FUNC) &_RcppQuaternions_AngleAxis2matrix, 2},
    {"_RcppQuaternions_normalized", (DL_FUNC) &_RcppQuaternions_normalized, 1},
    {"_RcppQuaternions_slerp_", (DL_FUNC) &_RcppQuaternions_slerp_, 3},
    {"_RcppQuaternions_rversor_", (DL_FUNC) &_RcppQuaternions_rversor_, 0},
    {"_RcppQuaternions_rversors_", (DL_FUNC) &_RcppQuaternions_rversors_, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppQuaternions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
